version: "3.8"

networks:
  filament:
    driver: bridge

volumes:
  filament-mysql:
    driver: local

services:
  proxy-server:
    container_name: nginx
    image: nginx:alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - filament
    depends_on:
        - php-fpm
        - pgsql

  php-fpm:
    container_name: filament
    build:
        context: .
        dockerfile: Dockerfile
    image: filament:latest
    volumes:
      - ./:/var/www/html
    networks:
      - filament

  mysql-database:
      container_name: mysql
      image: 'mysql:8.1'
      ports:
          - '${FORWARD_DB_PORT:-3306}:3306'
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
      volumes:
          - 'filament-mysql:/var/lib/mysql'
          - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
      networks:
          - sail
      healthcheck:
          test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
          retries: 3
          timeout: 5s
